server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index testclient.html;

    location ~* \.(?:css|js|mjs|json|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|map)$ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /testclient.html;
    }
}
